version: '3.8'
services:
  postgres_sql:
    image: postgres:latest
    container_name: postgres_sql
    restart: always
    environment:
      POSTGRES_DB: ticketing_app_db
      POSTGRES_USER: ziya
      POSTGRES_PASSWORD: Bismillah
    ports:
      - "5433:5432"
#      - "5432:5432"
    volumes:
      - ticketing_app_data:/var/lib/postgresql/data
    networks:
      - ticketing-app-net

  ticketing-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-app            # if we don't give image by default image name is [project-name]_[service-name]
    container_name: ticketing_app
    restart: always
    environment:
      SERVICE_PORT: 8088
      HOSTNAME: postgres_sql  # This should match the service name of the PostgreSQL container
      DB_NAME: ticketing_app_db
      USER_NAME: ziya
      PASSWORD: Bismillah
    ports:
      - "8088:8080" # This should be 8080 otherwise doesn't know
    depends_on:
      - postgres_sql
    networks:
      - ticketing-app-net

volumes:
  ticketing_app_data:
    name: ticketing_app_data # by default volume name is [project-name]_[volume-name]

networks:
  ticketing-app-net:
    name: ticketing-app-net # by default network name is [project-name]_[network-name]
    driver: bridge
