spring:
  datasource:
    url: jdbc:postgresql://${HOSTNAME}:5432/${DB_NAME}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  #flyway:
  #baseline-on-migrate: true
  #enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: cydeo.ticketing@gmail.com
    password: uaiw wvms yzqu ybdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  sql:
    init:
      mode: always

host-service-port: ${SERVICE_PORT}