spring:
  datasource:
    url: jdbc:postgresql://mydbinstance.clq8wogyshd2.eu-central-1.rds.amazonaws.com:5432/ticketing_app_db
    username: ziya
    password: Bismillah
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

#  flyway:
#  baseline-on-migrate: true
#  enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: cydeo.ticketing@gmail.com
    password: uaiw wvms yzqu ybdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  sql:
    init:
      mode: always

host-service-port: http://ec2-3-79-115-173.eu-central-1.compute.amazonaws.com:8080